version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package

cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - target/spring-boot-elk-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes